### ISSUE TITLE
Document extension points

### ISSUE THREAD

**Issue by rockyallen** [dobladez/antdoclet#3]
Currently only documents nested elements if the element is implemented by a concrete class, ie has methods like

```
addConcreteClass(ConcreteClass c)
```

Should also allow for extension points, ie where the element is an interface or extensible base class.
The method protoypes for these look like:

```
add(BaseClass c)
```

or

```
addConfigured(BaseClass c)
```

**Comment by dobladez** [comment]
Covered by pr #4
